function txt = contents_report_2_markdown(contents_file, options)
%CONTENTS_REPORT_2_MARKDOWN  Convert Contents.m MATLAB index file into formatted Contents for README.md
%
% Syntax:
%   txt = utils.contents_report_2_markdown(contents_file);
%   txt = utils.contents_report_2_markdown(contents_file, 'Name', value, ...);
%
% Example 1 (local Contents.m):
%   txt = utils.contents_report_2_markdown('Contents.m');
%
% Example 2 (full Contents.m path):
%   txt = utils.contents_report_2_markdown('D:/MyRepos/Repo/+package_submodule/Contents.m');
%
% Inputs:
%   contents_file {mustBeTextScalar, mustBeFile} - Name of Contents.m file
%       you want to parse. Note that Contents.m is expected to generally be
%       in the format that is auto-generated by running a Contents Report
%       from the MATLAB IDE. 
%
% Options:
%   'Verbose' (1,1) logical = true -- Set false to suppress Command Window output print of parsed README text.
%
% Output:
%   txt - Formatted text that can be pasted into README.md.
%           (Should be the same as what is printed to Command Window when
%           'Verbose' option is set to true). 
%
% See also: Contents
%#ok<*AGROW>

arguments
    contents_file {mustBeTextScalar, mustBeFile}
    options.Verbose (1,1) logical = true;
end

fid = fopen(contents_file, "r");
in = textscan(fid, '%%%s', 'Delimiter', '\n');
fclose(fid);
in = in{1};
in(cellfun(@isempty, in)) = [];
N = numel(in);
fprintf(1,'Please wait, parsing <strong>%s</strong> (%d lines)...000%%\n', contents_file, N);
tmp = strsplit(in{1}, ' ');
tmp(cellfun(@isempty, tmp)) = [];
txt = [sprintf('# %s #  ', tmp{1}), newline, sprintf('%s  ', strjoin(tmp(2:end), ' ')), newline, newline, '## Contents ##  ', newline];
fprintf(1,'\b\b\b\b\b%03d%%\n', round(1*100/N));
for ii = 2:N
    tmp = in{ii};
    if startsWith(tmp, '%')
        tmp = tmp(2:end);
        tmp = strtrim(tmp);
        txt = [txt, newline, sprintf('### %s ###  ', tmp), newline];  
    else
        tmp = strsplit(tmp, '-');
        tmp{1} = strtrim(tmp{1});
        tmp{2} = strtrim(strjoin(tmp(2:end), '-'));
        if ~endsWith(tmp{2}, '.')
            tmp{2} = [tmp{2}, '.'];
        end
        txt = [txt, sprintf(' + [%s](%s.m) - %s  ', tmp{1}, tmp{1}, tmp{2}), newline];
    end
    fprintf(1,'\b\b\b\b\b%03d%%\n', round(ii*100/N));
end
txt = [txt, newline];
if options.Verbose
    clc;
    fprintf(1, '\n%s', txt);
end

end