function output_folder = generate_output_container_folder(name, options)
%GENERATE_OUTPUT_CONTAINER_FOLDER  Generate output folder (windows-like) path-string.
%
% Syntax:
%   output_folder = utils.generate_output_container_folder(name,'Name',value,...);
%
% Example:
%   [root_folder,stem,~] = fileparts(mfilename('fullpath'));
%   output_folder = utils.generate_output_container_folder(stem, ...
%                   'RootFolder', root_folder);
%
% Inputs:
%   name - Name of container-folder. The actual output folder goes in this
%           folder, which is generated by combining the 'RootFolder' option
%           (default is the current workspace folder) with each cell
%           element as one sub-folder level from 'OutputRoot' option. 
%       Using the default options, in-practice this results in the output 
%       folder name of:
%       '<workspace folder>'/'output'/'<yyyy-mm-dd>'/name/v1
%       Where '<yyyy-mm-dd>' would be the current date, so you could get
%       for example:
%
%           'D:/MyRepos/Workspace/output/2023-09-28/myName/v1'
%
%       Once this output folder has been generated, then if this function
%       is called again, it will instead return:
%
%           'D:/MyRepos/Workspace/output/2023-09-28/myName/v2'
%
%       So it is just a convenient way to auto-increment the output folder
%       where batch runs are saved for example if you are iterating models
%       in a script and want to copy current version of script into the
%       folder where outputs are kept at the end of the script, so that you
%       know exactly what parameters were used when running the model.
%
% Options:
%     options.RootFolder {mustBeTextScalar} = pwd;
%     options.OutputRoot cell = {'output', sprintf('%04d-%02d-%02d',year(today),month(today),day(today))};
%
% Output:
%   output_folder - The container folder for output data/figures/etc.
%
% See also: Contents

arguments
    name {mustBeTextScalar}
    options.RootFolder {mustBeTextScalar} = pwd;
    options.OutputRoot cell = {'output', sprintf('%04d-%02d-%02d',year(today),month(today),day(today))};
end

output_folder_search = fullfile(options.RootFolder, options.OutputRoot{:}, name);
F = dir(fullfile(output_folder_search, 'v*'));
if isempty(F)
    output_folder = fullfile(output_folder_search, 'v1');
else
    model_num = nan(size(F));
    for iF = 1:numel(F)
        tmp = strrep(F(iF).name, 'v', '');
        model_num(iF) = str2double(tmp);
    end
    model_num(isnan(model_num)) = [];
    if isempty(model_num)
        model_num = 1;
    else
        model_num = max(model_num) + 1;
    end
    output_folder = fullfile(output_folder_search, sprintf('v%d',model_num));
end

end